# Generated by Django 3.0 on 2021-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20210314_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_weekly_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
