# Generated by Django 3.0 on 2021-03-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointments_is_weekly_repeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='is_weekly_repeat',
            new_name='repeat_weekly',
        ),
    ]
