# Generated by Django 3.0 on 2021-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='days',
            field=models.ManyToManyField(null=True, to='appointments.Days'),
        ),
    ]
