# Generated by Django 3.0 on 2021-03-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20210314_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='appointments.Days'),
        ),
    ]
