# Generated by Django 3.0 on 2021-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20210314_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='timezone',
            field=models.CharField(choices=[('', 'TIMEZONE1'), ('TIMEZONE2', 'TIMEZONE2'), ('TIMEZONE3', 'TIMEZONE3')], default='TIMEZONE1', max_length=120),
        ),
    ]
